### ISSUE TITLE
Move homepage away from Google Code

### ISSUE THREAD

**Issue by ryandesign** [videlalvaro/mypeb#10]
The readme still says:

> Checkout our website for complete manual http://mypeb.googlecode.com

You should move that web site somewhere else since Google Code has shut down.

GitHub Pages is a possibility.

**Comment by videlalvaro** [comment]
Feel free to send PRs for every feature you deem necessary

**Comment by ryandesign** [comment]
Sorry, it's not my job to work on your software.

**Comment by videlalvaro** [comment]
LMAO. This is the most entitled reply I've ever seen from an open source
user.

**Comment by ryandesign** [comment]
I'm a manager of the MacPorts project. In addition to dealing with management issues and our server infrastructure, I maintain the MacPorts ports for hundreds of software packages, including mypeb. I don't have time to be involved with the actual software development of all of those projects.

I noticed problems in your software. As a courtesy, I reported those issues to you. It's up to you to handle those reports in the way you see fit.

**Comment by videlalvaro** [comment]
I never asked for mypeb to be part of your MacPorts project. So deal with
it.

**Comment by ryandesign** [comment]
Sorry to hear you're an ass. You won't receive any further reports from me.

**Comment by videlalvaro** [comment]
Thanks for the personal attack.
